### ISSUE TITLE
Plugin Scripts and Stylesheets are not loading on the frontend 

### ISSUE THREAD

**Issue by joseabreu1985** [lightspeeddevelopment/lsx-videos#1]
**Describe the bug**
The latest version of LSX Videos plugin is not loading the JS file (lsx-videos.min.js) and the CSS file (lsx-videos.css) on the frontend of the site.

**To Reproduce**
1. Make sure that LSX theme and LSX Videos has the latest versions (and all LSX plugins)
2. Create a new video, and mark it featured 
3. In a page call the LSX Video shortcut

**Expected behavior**
The styles and scripts that make the slider work should be loaded and the carousel should be working.

**Screenshots**
Broken video section:
<img width="605" alt="broken-video-section" src="https://user-images.githubusercontent.com/20842182/73972512-bba16b80-48ff-11ea-8c99-b2c9ddbd50b0.png">

Working videos section
<img width="955" alt="working-video-section" src="https://user-images.githubusercontent.com/20842182/73972569-cfe56880-48ff-11ea-899f-b0835cc1c17b.png">

**Desktop:**
 - Happening in all browsers.

**Smartphone:**
 - Happening in all browser and OS.

**Additional context**
I have tested in my local and the function that is calling those files has this argument `LSX_VIDEOS_VER` that when is removes called the files.

**Comment by viscosho** [comment]
@joseabreu1985  I have fixed this issue on this PR: https://github.com/lightspeeddevelopment/lsx-videos/pull/2
Please review and test.
